[package]
name = "tetris-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tetris-core = { path = "../tetris-core" }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
