[package]
name = "tetris-core"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
instant = "0.1"
crc = "3.4.0"

[lints]
workspace = true

[dev-dependencies]
rstest.workspace = true
proptest.workspace = true
criterion.workspace = true
bincode = "1.3"

[[bench]]
name = "engine_bench"
harness = false
