[package]
name = "tetris-net"
version.workspace = true
edition.workspace = true

[dependencies]
tetris-core = { path = "../tetris-core" }
tetris-protocol = { path = "../tetris-protocol" }
renet = "2.0"
tokio = { version = "1.52", features = ["full"] }
serde.workspace = true
bincode = "1.3"
thiserror.workspace = true
slotmap = "1.1"
uuid = { version = "1", features = ["v4"] }
mdns-sd = "0.11"

[lints]
workspace = true

[dev-dependencies]
rstest.workspace = true
tokio-test = "0.4"

[[bench]]
name = "macro_bench"
harness = false
